/* Presenter notes, keyed by step id. Loaded by internal.html only; the customer page never ships this file. */
window.NOTES = {
  hero: "This is the integration strategy for Stage 1: how every franchise's job data gets into one trusted record, and how CJ sees it.",
  "1.1": "A water loss is dispatched to the Wichita franchise. They log it in Dash and accept it, the way they do today. Nothing about their day changes. Watch the right side. (Confirm with CJ where the dispatch time originates.)",
  "1.2": "One System API per platform speaks Dash and translates it into PuroClean's format. One Process API enriches it from FranConnect and checks it. Each translation is built once.",
  "1.3": "Within the 5-minute cycle: in this run, 41 seconds from the poll to the lake. It's an upsert, so if Dash sends the job again we update it rather than duplicate it.",
  "2.1": "CJ called this the Rosetta Stone. 'First on site,' 'arrive on site,' 'job began': all of them become Started, PuroClean's term. Dash already uses the standard. These are PuroClean's own 18 Dates; PuroClean owns the definitions (owner still to agree) and MuleSoft enforces them. Confirm whether 'PuroLogic' is the name they use.",
  "2.2": "Adding a platform means one new System API and its mapping, typically a few weeks of build and test. Everything downstream is reused. That's the difference between a feed and a platform.",
  "3.1": "Only four things need to be as live as possible, CJ's words. We spend real-time effort only where the SLA needs it; everything else runs once a day. We'll confirm which four with CJ.",
  "3.2": "The RD finds out while it can still be fixed, not in tomorrow's report. Who gets these alerts, and by which channel, is ours to design with CJ.",
  "4.1": "Robert put it best: we're not passing garbage to the data lake. Bad records are held back with a reason, not silently loaded, and their SLA clocks keep running.",
  "4.2": "Under 20% usable before MuleSoft. This is how we watch that number move, franchise by franchise.",
  "5.1": "Today CJ runs the SLA report in two minutes; an RD takes two hours, and nobody has a network view. Here it's three clicks for anyone with access, on all four platforms.",
  "5.2": "Twelve or thirteen RDs, one dashboard, each sees their own region. No copies, no exports. How many RD seats Stage 1 includes is a licensing decision.",
  "5.3": "Benchmarking was on CJ's list. Financials come later with QuickBooks; we're showing where they'll land.",
  "5.4": "Every number on CJ's screen traces back to a field, in a specific platform, through a specific API. When someone asks 'is this right?', this is the answer.",
  "6.1": "CJ's planning for 900. The integration doesn't change shape: the same two replicas carry the full network, and a storm surge autoscales for an afternoon. Confirm what '30 to 50' meant before using the 50 stop.",
  "6.2": "This is the 'bazooka' question. You don't start with the bazooka. Wave 1 is Dash and FranConnect. Every franchise after that is a row in a mapping table, not a project.",
  "7.1": "Vendors will have bad days. The question is whether you find out from a monitor or from CJ.",
  "7.2": "Seventeen minutes, zero data lost, and nobody had to be watching. The fix knowledge lives in the runbook and the platform, not in one person's head. Who is on call, PuroClean IT or the partner, is still to decide.",
  "7.3": "SOC 2 was the gate. It's there, alongside ISO 27001 and the rest. And control stays with you: MuleSoft runs the platform, PuroClean owns the policies, the credentials and the definitions.",
  "7.4": "Only use CJ's lottery line if CJ is comfortable with it at the dry run. The point: the knowledge stays with PuroClean. Nick's still the architect; he just isn't the only one who can keep it running.",
  "8.1": "CJ wants to be proactive, not reactive. This is the first step: the dashboard comes to you.",
  "8.2": "Dashboards first, with an AI proactive mindset. Weather, agents and a unified customer view come once the data is trusted. None of it is Stage 1.",
  arch: "Tap any block for what it does. This is the whole Stage 1 picture on one page.",
  close: "Wave 1 is Dash and FranConnect, targeting mid-January and earlier if the partner plan allows. Everything after that reuses what we build.",
};
