/* Presenter notes. Loaded ONLY by internal.html — never by index.html.
   Keyed by step ID. Chapter question appears automatically in the talk bar.
   Handoff lines help you segue into the next beat. */
window.NOTES = {
  hero: "Welcome. This is a 14-stop short path or a full 30-minute run. Pick Short path to start — you can switch any time. Four people in the story: Alex, a franchise project manager; Jordan, a corporate regional director; CJ Bailey; and Nick Hindle, the CIO.",
  today: "The framing slide: why five connections don't mean five projects. Great to run before Chapter 1 if you have time.",

  "1.1": "Clicks: Water, Save, Accept job. Set the scene: corporate sees less than 20 percent of franchise jobs today. Franchises asked for choice, so PuroClean is offering four approved job management platforms and requiring one of them by January 1. The first goal is measuring adoption, so this chapter shows a franchise PM or owner working in Dash and how that job reaches your dashboard. The franchise's day doesn't change. Alex logs the job in Dash exactly as today; Dash stores Water as its own code. MuleSoft will pick it up on its own on the next five-minute cycle. Nothing to install, nothing to change.",
  "1.2": "Clicks: Loss type, Received/Accepted, Franchise. Then the Rosetta animation plays automatically — about 4 seconds, no click needed. Each click shows one translation: Dash's H2O becomes Water, three local times become UTC PuroLogic Dates, and the Dash account number becomes PuroClean Wichita East with its region from FranConnect. The Rosetta animation shows all four platforms' loss codes converging to one value. The franchise never sees any of this. On the right, the three shaded lanes are MuleSoft's API-led layers: System APIs connect each platform, the Process API combines, cleans and routes, and the Experience API delivers alerts to people. Say 'one standard time', not UTC, to the room.",
  "1.3": "Clicks: Address, Received/Accepted, Contacted. Address is part of the dedupe key, so the quality check runs; the dates land in 11:11 with a MERGE; Contacted is the next step, and its 30-minute clock is now running on the corporate side. 41 seconds after MuleSoft picked it up.",
  "1.4": "Clicks: Email, Initial contact template, Send. The PM never types a time: logging the email sets Contacted, and that's the change MuleSoft picks up. Only the four SLA milestones ride the fast lane — contacted, inspected, dispatch, received. Everything else syncs at 2 AM. Fast where it matters, cheap everywhere else.",
  "1.5": "Clicks: PSA, Albi, JobSite. Same job, four platforms. PSA calls it 'First On Site', Albi calls it 'Arrive On Site'. All four map to 'Started' in the PuroLogic Dates. One mapping per platform, built once, reused forever. Meanwhile, it's now 8:05 AM.",

  "2.1": "Clicks: the text (owner's phone), the alert (Jordan's phone), Acknowledge. Two phones side by side: the franchise owner's text on the left, Jordan's heads-up on the right. Nick already built a text to franchises; today someone sends it by hand. Here it goes out automatically, in seconds. Point at the delivery rules card: owner by text, RD by email and Tableau Mobile, VP only if no one acknowledges. Frame this as support, not policing. CJ: the RD is not the one calling the customer, the franchise is. Jordan's heads-up is awareness; repeat misses become his performance conversation (chapter 8). After Acknowledge there are no more clicks: the owner calls the customer, the next PSA poll closes the SLA, and the owner gets a confirmation text. If asked about cost per text: separate conversation, no figures.",

  "3.1": "Clicks: Save, Save, Save. Three saves in Dash from a multi-location account: a duplicate, a job with no loss type, and a clean inspection update. The 10:15 poll merges the duplicate, holds the incomplete one with a reason code, and loads the clean one. Nothing is silently thrown away. Why it matters to the franchise: dirty data is why less than 20 percent is usable today, and this is how it gets fixed without extra work for the PM.",
  "3.2": "Clicks: Missing loss type, Wichita East, Share. Usable data started below 20 percent in November — it's at 64 percent now. CJ drills to Wichita East's held records, including the Derby job saved at 10:12 AM (step 3.1 on the full run), and shares the filtered view with the Central RD.",

  "4.1": "Clicks: Kansas, Water + Fire, the job. Network to one job in three clicks — and a By franchise location sheet showing Wichita East (KS-0412, 7 jobs) and Wichita West (KS-0418, 4 jobs). Every click is a live query to 11:11 through Tableau Bridge — the SLA milestones are minutes old. This is the view that doesn't exist today. Say 'a fraction of a second', not 'a seventh of a second'.",
  "4.2": "Clicks: Subscribe, Subscribe & create alert, Preview alert email. Jordan signs in as the West RD and only sees West Region rows. One dashboard, zero copies. Two automations: a weekly digest and a data-driven alert if on-time completion drops below 80 percent.",
  "4.3": "Clicks: Cycle time, Who's in the average?, Compare to Central. Wichita East ranks 27th of 275 on cycle time (top 10%). The average only counts franchises with usable data (64% today, from Data Health), so 155 are left out until they pass the quality rules. That number shrinks as each wave finishes.",
  "4.4": "Clicks: the On-time completion tile, Upstream table, Downstream. The lineage traces the number back through Tableau and MuleSoft to the exact PSA field, then forward to every workbook and Tableau metric that uses it.",
  "4.5": "Clicks: ask, drag Loss type, Save. CJ asks Tableau Agent a question in plain English. No IT ticket, no new pipeline, no extract. His question asks for West, so the agent filters to West. Row-level security still applies on the certified data source: CJ sees every region, and an RD asking the same question would only ever see their own.",

  "5.1": "Clicks: 430, 900, Storm surge. Point at the map filling in and the counters: volume goes \u00d78, then \u00d717, but the banner stays at zero code changes, zero redeploys, two replicas. Only CPU moves. Storm surge: hailstorm over DFW, the chart breaks through the old axis, Anypoint MQ holds the backlog while CloudHub 2.0 autoscales to four replicas, and the backlog drains to zero. Nothing is dropped. Then the storm alert: the same notification-api that sends SLA alerts tells the DFW regional director and the local franchise owners that volume is 4x, so they can plan crews and equipment. If asked about weather: forecasting and proactive outreach are the AI agent use case after Stage 1 (What's next, 8.3).",
  "5.2": "Clicks: Connect franchise, Dayton North, Connect. FranConnect already knows the franchise; MuleSoft checks the PSA account; Connect adds one row to a config table. No deployment, no code. The admin page is illustrative: a light PuroClean screen over the account map that calls the same franconnect-sapi and psa-sapi. Dayton North's first 23 jobs flow on the next five-minute cycle.",
  "5.3": "Clicks: the template, Open in Code Builder, Deploy Application. A fifth SPAR platform is one new System API from an Exchange template, built in Code Builder and deployed from Runtime Manager. Point at the flow: only the System APIs lane changes. The canonical model, Process API, quality rules, 11:11 and Tableau are reused as-is. Downstream: zero changes.",

  "6.1": "Clicks: the amber tile, PSA, View franchises. PSA went down at 2:14 PM. MuleSoft retried three times, paused PSA polling and held the watermark — and instantly alerted CJ and the on-call engineer, naming the System layer. Today, if a feed stops, nobody's told. Here, CJ and on-call know within seconds. The System APIs lane in the console turns red. CJ sees the status MuleSoft writes, the probe running every minute, and exactly which franchises are affected.",
  "6.2": "Clicks: the alert, Acknowledge, View trace. The on-call owner gets an email with the franchise count, the watermark and a runbook link. The trace shows every hop. At 2:31 PM PSA recovers, and MuleSoft catches up all 21 changes in order. Zero lost, zero duplicated.",

  "7.1": "Clicks: Send valid request, JSON Threat Protection, Send malformed payload. Every inbound call passes four API Manager policies. The limits are configuration, not code, and the malformed payload is blocked at the gateway — psa-sapi never sees it.",
  "7.2": "Clicks: psa-sapi, the runbook, the PSA monitor. Every asset has an owner, a spec and a runbook — the same runbook the 2:15 PM alert linked to. Five functional monitors, one per connection. Any team member can pick up a piece: the team shares the load, and no one is a single point of contact.",

  "8.1": "Clicks: the West Region card, Fresno East, Open in Tableau. Jordan's Tableau morning digest at 7:30 AM PT: West is up about 20% on last year, but Fresno East is down about 30%. Jordan spots it before anyone calls. The product name is Tableau Pulse if anyone asks, but say 'Tableau morning digest' or just 'Tableau' on screen. Don't say 'Pulse' — CJ's first reaction was that the word clashes with PuroClean's franchise newsletter.",
  "8.2": "Clicks: Ohio, Dayton, Dayton North. Explain Data traces the spike: Columbus is seasonal, Dayton is the franchise that connected Tuesday, and its data shows jobs from before Tuesday that corporate couldn't see until then. Data working as designed.",
  "8.3": "Clicks: Stage 1, Stage 2, Stage 3. Stage 1 builds the foundation, Stage 2 reuses it for compliance, Stage 3 adds one QuickBooks Online connector. Weather overlays, AI agents and a unified customer view come after. None of this is Stage 1, but Stage 1 makes it possible.",

  arch: "The full architecture on one page. Everything that appeared in the demo is here.",
  wrap: "No clicks. The recap adapts to the path you're on: on Short path it's the moments you just walked; toggle to Full run and it fills in with the extra stops and a roadmap strip. Tie a bow on the story: one job in Dash became one trusted record that everyone can see and act on, from Alex to Nick. Then press Next for the questions and next steps.",
  close: "Eight questions, eight answers. The next steps are the same five we've discussed: confirm the SLA milestones, agree the canonical model owner, design the 11:11 connection with Nick, introduce the partners, and agree the mutual plan.",
};
